language:
  - node_js
node_js:
  - node
services:
  - sqlite3
srcipt: node_modules/karma/bin/karma start my.conf.js --single-run
before_script:
  - npm install
os:
  - macos
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start