const main = require('./js/main.js')
//const menu = require('./js/menu.js')
const gui = require('nw.gui')
const win = gui.Window.get()
const db = require('./js/db.js')
win.showDevTools()

main.init()
db.init()
//menu.initMenu()