INSERT INTO NOTES(NOTENAME, CONTENT)
VALUES ("note1", "content1");
INSERT INTO NOTES(NOTENAME, CONTENT)
VALUES ("note2", "content2");
INSERT INTO NOTES(NOTENAME, CONTENT)
VALUES ("note3", "content3");
INSERT INTO NOTES(NOTENAME, CONTENT)
VALUES ("note4", "content4");